# Generated by Django 5.2.1 on 2025-11-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_alter_membresia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroactividad',
            name='detalles',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='objetivo_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
