# Generated by Django 5.2.1 on 2025-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_critico',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad mínima deseada. Si el stock operativo baja de este número, se generará una alerta. Dejar en 0 para desactivar.', verbose_name='Stock Crítico / Mínimo'),
        ),
    ]
