# Generated by Django 5.2.1 on 2025-11-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0003_producto_stock_critico'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamodetalle',
            name='cantidad_extraviada',
            field=models.PositiveIntegerField(default=0, verbose_name='Cant. Extraviada/Dañada'),
        ),
    ]
