# Generated by Django 5.2.1 on 2025-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0004_prestamodetalle_cantidad_extraviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamodetalle',
            name='fecha_ultima_devolucion',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última devolución o reporte de pérdida parcial.', null=True, verbose_name='Última Actualización'),
        ),
    ]
