# Generated by Django 5.2.1 on 2025-11-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentohistorico',
            name='es_confidencial',
            field=models.BooleanField(default=False, help_text='Si se marca, el documento solo será visible para usuarios con permisos de gestión (Oficiales).', verbose_name='Confidencial'),
        ),
        migrations.AddField(
            model_name='documentohistorico',
            name='palabras_clave',
            field=models.CharField(blank=True, help_text='Términos clave separados por comas para mejorar la búsqueda.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentohistorico',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, help_text='Referencia topográfica del original (Ej. Estante A, Caja 3).', max_length=255, null=True),
        ),
    ]
