# Generated by Django 5.2.1 on 2025-11-20 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Alergia',
                'verbose_name_plural': 'Alergias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cirugía',
                'verbose_name_plural': 'Cirugías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Contacto de Emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Usar punto (.) para decimal', max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('altura_mts', models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 1.75', max_digits=3, null=True, verbose_name='Altura (mts)')),
                ('presion_arterial_sistolica', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Presión arterial Sistólica')),
                ('presion_arterial_diastolica', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Presión arterial Diastólica')),
                ('observaciones_generales', models.TextField(blank=True, help_text='Anotaciones relevantes no cubiertas en otros campos.', null=True, verbose_name='Observaciones Generales')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
            },
        ),
        migrations.CreateModel(
            name='FichaMedicaAlergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, help_text="Ej: 'Reacción grave', 'Solo produce picazón'", max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Alergia de Ficha',
                'verbose_name_plural': 'Alergias de Ficha',
            },
        ),
        migrations.CreateModel(
            name='FichaMedicaCirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cirugia', models.DateField(blank=True, null=True, verbose_name='Fecha (aprox.)')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Cirugía de Ficha',
                'verbose_name_plural': 'Cirugías de Ficha',
                'ordering': ['-fecha_cirugia'],
            },
        ),
        migrations.CreateModel(
            name='FichaMedicaEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, help_text="Ej: 'Crónica', 'En tratamiento'", max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Enfermedad de Ficha',
                'verbose_name_plural': 'Enfermedades de Ficha',
            },
        ),
        migrations.CreateModel(
            name='FichaMedicaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis_frecuencia', models.CharField(blank=True, help_text="Ej: '10mg cada 8 horas'", max_length=100, null=True, verbose_name='Dosificación')),
            ],
            options={
                'verbose_name': 'Medicamento de Ficha',
                'verbose_name_plural': 'Medicamentos de Ficha',
            },
        ),
        migrations.CreateModel(
            name='GrupoSanguineo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Grupo sanguíneo',
                'verbose_name_plural': 'Grupos sanguíneos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SistemaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sistema de salud',
                'verbose_name_plural': 'Sistemas de salud',
                'ordering': ['nombre'],
            },
        ),
    ]
