# Generated by Django 5.2.1 on 2025-11-20 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_medica', '0001_initial'),
        ('gestion_voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoemergencia',
            name='voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='gestion_voluntarios.voluntario'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='voluntario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='gestion_voluntarios.voluntario', verbose_name='Voluntario'),
        ),
        migrations.AddField(
            model_name='fichamedicaalergia',
            name='alergia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.alergia'),
        ),
        migrations.AddField(
            model_name='fichamedicaalergia',
            name='ficha_medica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='gestion_medica.fichamedica'),
        ),
        migrations.AddField(
            model_name='fichamedicacirugia',
            name='cirugia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.cirugia'),
        ),
        migrations.AddField(
            model_name='fichamedicacirugia',
            name='ficha_medica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='gestion_medica.fichamedica'),
        ),
        migrations.AddField(
            model_name='fichamedicaenfermedad',
            name='enfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.enfermedad'),
        ),
        migrations.AddField(
            model_name='fichamedicaenfermedad',
            name='ficha_medica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades', to='gestion_medica.fichamedica'),
        ),
        migrations.AddField(
            model_name='fichamedicamedicamento',
            name='ficha_medica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='gestion_medica.fichamedica'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='grupo_sanguineo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.gruposanguineo', verbose_name='Grupo Sanguíneo'),
        ),
        migrations.AddField(
            model_name='fichamedicamedicamento',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.medicamento'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='sistema_salud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_medica.sistemasalud', verbose_name='Sistema de Salud'),
        ),
        migrations.AlterUniqueTogether(
            name='fichamedicaalergia',
            unique_together={('ficha_medica', 'alergia')},
        ),
        migrations.AlterUniqueTogether(
            name='fichamedicaenfermedad',
            unique_together={('ficha_medica', 'enfermedad')},
        ),
        migrations.AlterUniqueTogether(
            name='fichamedicamedicamento',
            unique_together={('ficha_medica', 'medicamento')},
        ),
    ]
