# Generated by Django 5.2.1 on 2025-12-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_medica', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'default_permissions': [], 'ordering': ['nombre', 'concentracion'], 'permissions': [('sys_view_medicamento', 'System: Puede ver Medicamentos'), ('sys_add_medicamento', 'System: Puede agregar Medicamentos'), ('sys_change_medicamento', 'System: Puede cambiar Medicamentos'), ('sys_delete_medicamento', 'System: Puede eliminar Medicamentos')], 'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AddField(
            model_name='medicamento',
            name='clasificacion_riesgo',
            field=models.CharField(blank=True, choices=[('', 'Neutro / Sin Alerta'), ('ANTICOAGULANTE', 'ANTICOAGULANTE'), ('COAGULANTE', 'COAGULANTE / HEMOSTÁTICO'), ('ANTIPLAQUETARIO', 'ANTIPLAQUETARIO')], default='', max_length=20, verbose_name='Clasificación de Riesgo'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='concentracion',
            field=models.IntegerField(blank=True, help_text='Ej: 500', null=True, verbose_name='Dosis/Cantidad'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='unidad',
            field=models.CharField(choices=[('mg', 'mg (Miligramos)'), ('ml', 'ml (Mililitros)'), ('gr', 'gr (Gramos)'), ('mcg', 'mcg (Microgramos)'), ('g/ml', 'g/ml'), ('mg/ml', 'mg/ml'), ('ui', 'UI (Unidades Int.)'), ('%', '% (Porcentaje)'), ('puff', 'Puff/Inhalación'), ('comp', 'Comprimido(s)'), ('cap', 'Cápsula(s)'), ('gotas', 'Gotas'), ('amp', 'Ampolla'), ('unid', 'Unidad(es)')], default='mg', max_length=10, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(help_text='Ej: Paracetamol', max_length=100, verbose_name='Nombre del Fármaco'),
        ),
        migrations.AlterUniqueTogether(
            name='medicamento',
            unique_together={('nombre', 'concentracion', 'unidad', 'clasificacion_riesgo')},
        ),
    ]
